name: SQL_DatabricksSharedBasic
description: ''
version: '1.0'
author: null
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/REL_DB_Databricks:
    name: REL_DB_Databricks
    description: REL_DB_Databricks
    fabricUID: 5286
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: prophecy_internal_jobs
    scheduleCron: 0 0 0 * * ? 2090
    timeout: null
    alerting:
      emails: abhisheks@prophecy.io,abhisheks@simpledatalabs.com
      onStart: false
      onSuccess: true
      onFailure: true
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: false
    createdAt: '2023-04-21 14:08:05'
    modifiedAt: '2023-04-26 08:00:12'
    author: abhisheks+shared@prophecy.io
  jobs/REL_DB_AIRFLOW:
    name: REL_DB_AIRFLOW
    description: REL_DB_AIRFLOW
    fabricUID: 5295
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0 17 * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-04-21 14:20:18'
    modifiedAt: '2023-04-26 06:19:50'
    author: abhisheks+shared@prophecy.io
functions:
  author: null
  createdAt: '2023-04-12 09:18:21'
  modifiedAt: '2023-04-12 09:18:21'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/tpcds_uitesting_shared_1:
    name: tpcds_uitesting_shared_1
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - models/tpcds/tpcds_uitesting_shared_1.sql
    - .prophecy/ide/models/tpcds_uitesting_shared_1.json
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2023-04-19 14:31:39'
    modifiedAt: '2023-04-19 14:31:39'
  .prophecy/metadata/sqlmodels/env_uitesting_shared_useallmodel_1:
    name: env_uitesting_shared_useallmodel_1
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - models/env_uitesting_shared_useallmodel_1.sql
    - .prophecy/ide/models/env_uitesting_shared_useallmodel_1.json
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2023-04-12 10:03:43'
    modifiedAt: '2023-04-12 10:03:43'
  .prophecy/metadata/sqlmodels/env_uitesting_shared_parent_model_1:
    name: env_uitesting_shared_parent_model_1
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - models/mainmodels/env_uitesting_shared_parent_model_1.sql
    - .prophecy/ide/models/env_uitesting_shared_parent_model_1.json
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2023-04-12 09:20:52'
    modifiedAt: '2023-04-12 09:20:52'
  .prophecy/metadata/sqlmodels/env_uitesting_shared_child_model_1:
    name: env_uitesting_shared_child_model_1
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - models/mainmodels/env_uitesting_shared_child_model_1.sql
    - .prophecy/ide/models/env_uitesting_shared_child_model_1.json
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2023-04-12 09:20:35'
    modifiedAt: '2023-04-12 09:20:35'
  .prophecy/metadata/sqlmodels/env_uitesting_shared_mid_model_1:
    name: env_uitesting_shared_mid_model_1
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - models/mainmodels/env_uitesting_shared_mid_model_1.sql
    - .prophecy/ide/models/env_uitesting_shared_mid_model_1.json
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2023-04-12 09:19:50'
    modifiedAt: '2023-04-12 09:19:50'
sqlMacros:
  .prophecy/metadata/sqlmacros/qa_concat_function_main:
    name: qa_concat_function_main
    macroType: expression
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - macros/functions/qa_concat_function.sql
    - macros/functions/functions.yml
    createdAt: '2023-04-12 09:27:48'
    modifiedAt: '2023-04-12 09:27:48'
  .prophecy/metadata/sqlmacros/qa_select_all_not_null_gem:
    name: qa_select_all_not_null_gem
    macroType: query
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - macros/gems/qa_select_all_not_null_gem.sql
    - .prophecy/ide/macros/qa_select_all_not_null_gem.json
    - macros/gems/gems.yml
    createdAt: '2023-04-12 09:26:51'
    modifiedAt: '2023-04-12 09:26:51'
sqlSeeds:
  .prophecy/metadata/sqlseeds/raw_customers:
    name: raw_customers
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - seeds/raw/raw_customers.csv
    createdAt: '2023-04-12 09:25:50'
    modifiedAt: '2023-04-12 09:25:50'
sqlSources:
  .prophecy/metadata/sqlsources/spark_catalog_qa_database:
    name: spark_catalog.qa_database
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2023-04-12 09:22:07'
    modifiedAt: '2023-04-12 09:22:07'
    tables:
    - name: all_type_parquet
      description: null
      author: abhisheks+e2etests@prophecy.io
      createdAt: '2023-04-12 09:22:07'
      modifiedAt: '2023-04-12 09:22:07'
    - name: store_sales
      description: null
      author: abhisheks+e2etests@prophecy.io
      createdAt: '2023-04-19 17:49:01'
      modifiedAt: '2023-04-19 17:49:01'
    - name: item
      description: null
      author: abhisheks+e2etests@prophecy.io
      createdAt: '2023-04-19 17:49:08'
      modifiedAt: '2023-04-19 17:49:08'
    - name: date_dim
      description: null
      author: abhisheks+e2etests@prophecy.io
      createdAt: '2023-04-19 17:49:16'
      modifiedAt: '2023-04-19 17:49:16'
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: abhisheks+e2etests@prophecy.io
  createdAt: '2023-04-12 09:18:21'
  modifiedAt: '2023-04-12 09:18:21'
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
